services:
  certbot:
    container_name: certbot
    build:
      context: docker/certbot
    environment:
      DOMAIN: architecture.com.br
      EMAIL: admin@architecture.com.br
    volumes:
      - ./docker/ssl:/etc/letsencrypt
      - ./public:/var/www/public
    command: >
      certonly --webroot --webroot-path=/var/www/public
      --agree-tos --no-eff-email
      --email admin@architecture.com.br
      -d architecture.com.br
